### ISSUE TITLE
model testing

### ISSUE THREAD

**Issue by lkluo** [Scitator/TF-seq2seq#1]
Hi, this project is inspiring. Could you give example on mode testing?

**Comment by Scitator** [comment]
@lkluo Hello!

I create special branch with example notebooks - [link](https://github.com/Scitator/TF-seq2seq/tree/notebooks).

PS. for model usage you also need my [another repo](https://github.com/Scitator/rstools) with useful stuff.
`pip install git+https://github.com/Scitator/rstools.git
`

**Comment by lkluo** [comment]
HI Scitator,

Thank you very much for your reply. Oh yes, my fault.  This is helpful.
