### ISSUE TITLE
train data

### ISSUE THREAD

**Issue by lkluo** [Scitator/TF-seq2seq#3]
I found in train.txt data, the input contains {source} + {target} while output {target} + {source}. My understanding correct? If so, what is the advantage of using bilingual data for both encoder and decoder?

**Comment by Scitator** [comment]
Yes, its correct.

My personal preference :)
Main idea is to have better embeddings (+ some articles share this idea)

**Comment by lkluo** [comment]
thanks. although it was closed, could you provide some articles?
